name: resourcet-pool
version: 0.1.0.0
maintainer: Brandon Chinn <brandonchinn178@gmail.com>
category: Data, Database, Network, Conduit
synopsis: A small library to convert a Pool into an Acquire
description: |
  A small library to convert a Pool into an Acquire, allowing
  one to use the `resourcet` framework with a resource exported
  as a `Pool`.
license: BSD3
license-file: LICENSE

ghc-options: -Wall

library:
  source-dirs: src
  dependencies:
    - base >= 4.9 && < 5
    - resource-pool >= 0.2.1.0 && < 0.3
    - resourcet >= 1.1.2 && < 2
